### PR TITLE
Add NRQL alert condition and Synthetics alert condition

### PR DESCRIPTION
**Pull request by dthorsen**

### CODE REVIEW

**Comment by dthorsen** [comment]
I am working on adding some new functionality to the New Relic Terraform provider.

**Comment by paultyng** [comment]
Let me setup some CI real quick on this so we can at least get these tests exercised in PR's

**Comment by dthorsen** [comment]
Sounds good, thanks. I see some work was done for NRQL in in #5.  I haven't looked through that code yet to compare it to mine.

**Comment by paultyng** [comment]
I backed out that commit, I just saw it added 2 fields so didn't think it was an overlap, since this has coverage, I'd rather use it if it covers the same ground.

**Comment by paultyng** [comment]
@dthorsen travis support is added, can you rebase?

**Comment by dthorsen** [comment]
@paultyng Rebased

**Comment by RubyLi0612** [comment]
@dthorsen Hi. Thank you for the contribution on NRQL query condition. I was actually working on the same thing hoping that NRQL can be supported by terraform. Have you also modified the terraform-provider-newrelic repo for condition resource? I have another version of solution that seem to work fine for creating NRQL alert condition, which I tried by applying it onto a real NewRelic account. Yet I feel that your work is more comprehensive so i wonder if you have worked on the terraform side so that we can start to apply and see it!

**Comment by dthorsen** [comment]
@RubyLi0612 I have the NRQL conditions working on the terraform side. Code is available here:

https://github.com/dthorsen/terraform-provider-newrelic/tree/add_new_alert_conditions

I plan to PR this to terraform-providers once this PR is merged.

**Pull request merged**
