### PR TITLE
Adding support for Smart Host Not Reporting functionality

### PR DESCRIPTION
**Pull request by nathanweddle**
Updated version

New functionality will give the user the option to not fire an HNR alert on a clean shutdown.

### CODE REVIEW

**Comment by jthurman42** [comment]
Thanks for the contribution @nathanweddle !

Looks like TravisCI is flagging the builds as abuse. ( https://travis-ci.org/paultyng/go-newrelic/requests ).  A quick doc search looks like Travis wants everyone to login to their system to verify they are users ( https://travis-ci.community/t/some-pr-are-not-analyzed-with-message-abuse-detected/1191) Is that something you could do? Otherwise we'll need to redo the PR under another user (which will take a bit more time to do)

**Comment by nathanweddle** [comment]
Hi Jonathan, 

I just created my account in Travis CI. Do I need to do a commit to get it to kick off again? Thanks! 

Nathan

**Comment by nathanweddle** [comment]
@jthurman42 I created an account in Travis CI and kicked off another build, but it is still flagged as abuse

**Comment by jthurman42** [comment]
I'll try pushing it to the repo in another PR: #88

**Pull request closed without merging**
