### PR TITLE
add deployment api for listing deployments and creating deployments

### PR DESCRIPTION
**Pull request by oba11**
This pull request adds capability to add list deployments by application id and create deployment for an application

### CODE REVIEW

**Comment by paultyng** [comment]
This looks good to me, but would be good to get some tests in to cover the API interactions as well.

**Comment by oba11** [comment]
@paultyng Thanks for taking the time to review the PR, will add some tests in a bit

**Comment by oba11** [comment]
@paultyng added the tests as suggested, please let me know what you think.

**Review by paultyng — APPROVED** [review]

**Comment by oba11** [comment]
Thank you @paultyng

**Pull request merged**
